language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get install python3-tk -y
install: "pip install -r requirements.txt"
# command to run tests
script: pytest

