language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
env:
  - DISPLAY=:99.0
before_install:
  - sudo apt-get install python3-tk -y
  - sudo apt-get install python3-requests -y
  - sh -e /etc/init.d/xvfb start
script: pytest

